services:
  - type: web
    name: my-rails-app
    env: ruby
    region: oregon
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-rails-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
    autoDeploy: true
    healthCheckPath: "/"
    plan: free

databases:
  - name: my-rails-db
    region: oregon
    plan: free
